name = "day07"
version = "0.1.0"
defaultTargets = ["day07"]

[[lean_lib]]
name = "Day07"

[[lean_exe]]
name = "day07"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git  = "https://github.com/leanprover-community/mathlib4.git"
rev  = "v4.??.0"
